repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

templates: 
  default: &default
    namespace: backbone
    missingFileHandler: Warn

values:
  - ../environments/dev-secrets.yaml
  - ../environments/dev.yaml

releases:
- name: cert-manager
  chart: ./cert-manager
  installed: false
  version: 0.5.2
  disableValidation: true
  values:
    - ./cert-manager/values.yaml

- name: minio
  installed: false
  chart: ./minio
  version: 0.1.0
  <<: *default
  values:
    - ./minio/values.yaml

- name: postgresql
  installed: false
  chart: ./postgresql
  version: 11.9.13
  <<: *default
  values:
    - ./postgresql/values.yaml
    - global:
        postgresql:
          auth:
            postgresPassword: {{ .Values.secrets.db.password | quote }}
- name: redis
  installed: false
  chart: ./redis
  version: 3.0.0
  <<: *default
  values:
    - ./redis/values.yaml

- name: elasticsearch
  chart: ./elasticsearch
  version: 7.6.1
  installed: false
  <<: *default
  values:
    - ./elasticsearch/values.yaml
    - secret:
        password: {{ .Values.secrets.elasticsearch.password }}

- name: elasticsearch-data
  chart: ./elasticsearch-data
  installed: false
  version: 7.6.1
  <<: *default
  values:
    - ./elasticsearch-data/values.yaml

- name: kibana
  chart: ./kibana
  version: 1.0.0
  installed: false
  force: true
  <<: *default
  values:
    - ./kibana/values.yaml
    - ingress:
        hosts:
          - host: {{ .Values.global.domain }}
            paths:
              - path: /kibana
        tls: 
          - secretName: {{ .Values.global.domain }}-tls-certs
            hosts:
              - {{ .Values.global.domain }}



- name: kafka-kraft
  installed: false
  chart: ./kafka-kraft
  version: 1.0.0
  <<: *default
  values:
    - ./kafka-kraft/values.yaml
  set:
    - name: kraft.clusterId
      value: {{ .Values.secrets.kafka.clusterID }}

- name: ingress-nginx
  installed: true
  chart: ./ingress-nginx
  version: 4.10.0
  <<: *default
  values:
    - ./ingress-nginx/values.yaml
    - domain: {{ .Values.global.domain }}

- name: playground
  installed: false
  chart: ./playground
  version: 0.1.0
  <<: *default
  values:
    - ./playground/values.yaml
