repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: jaegertracing
  url: https://jaegertracing.github.io/helm-charts

values:
  - namespace: monitoring-helmfile
  - host: digit-lts.digit.org


releases:

- name: loki-stack
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: grafana/loki-stack
  version: 2.10.1
  values:
  - ./values/loki-stack.yaml

- name: kube-prometheus-stack
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: prometheus-community/kube-prometheus-stack
  version: 56.6.2
  values:
  - ./values/prometheus.yaml

- name: jaeger
  installed: false
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: jaegertracing/jaeger
  version: 1.0.0 
  values:
  - ./values/jaeger.yaml
  set:
    - name: query.ingress.hosts[0]
      value: "{{ .Values.host }}"

- name: grafana
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: grafana/grafana
  version: 7.3.0
  values:
  - ./values/grafana.yaml
  set:
    - name: ingress.hosts[0]
      value: "{{ .Values.host }}"
    - name: ingress.tls[0].hosts[0]
      value: {{ .Values.host | quote }}
