secrets:
    db:
        username: postgres
        password: adnsfbfbnvja
        flywayUsername: postgres
        flywayPassword: adnsfbfbnvja
    egov-filestore:
        awskey: nsbufjbasnvvnkjd
        awssecretkey: bxjcsncajsb
    egov-enc-service:
        master_password: demo
        master_salt: q7.fr.cr
        master_initialvector: 9J&asfgrU-H2
    egov-notification-sms:
        username: demo
        password: demo
    egov-notification-mail:
        mailsenderusername: demo@demo
        mailsenderpassword: demo
    egov-location:
        gmapskey: jbsdbvxmbsmnx
    kafka:
        clusterID: HshRPdVrWoB4kuTdEbawtq
    elasticsearch:
        password: jsme31bhRxdckMVznI3LB1PH
    oauth2-proxy:
        cookieSecret: qwgethjymnbv
        clientSecret: 3a08079easd9d8055470475696fd3baad5292
        clientID: QVbnq0L8npoyfxZs96wtBg==
    git-sync:
        ssh: |-
            -----BEGIN RSA PRIVATE KEY-----
            MIIEowIBAAKCAQEAqnSUESh+RbYEYOIbdUcYTZVLcdI2nE3D03v1MrjGS1C+KP4z
            b7U/M1sauoKtIwU3r/E/qhSNZFJWRIT3myofB8TB89zqyAxIp79ddawerXO5UQ7r
            hbd4SBqLokItw5E1/LV0GJy/914xTJAm5B8o/LO6nvwqCHIi/VRPau4N/dDOYyGN
            A7r9j3ov8gY28ieB3sPpAzkJg2/gJWW7ptpX1vvL7St6hCMoFENPXc4R5DO9kriu
            RM7MQlGcm5SORav5Ob97gjlG7q7SDjEYZCRmQ1k/kVWZDjTTPpsUweDf+V77bdm9
            rylhbccp0QG0aBJN4INKzJsxXQgwqBjJCN05cwIDAQABAoIBAHpfW3W+BnlxpU8Q
            xPm7Yr1AM3uxmTc5tR79XRlfAi1L+Flhtfe6vXbXLyc7baU4t7P+lOA8BQ5C9mAW
            vdSNtt1S6pNyxLN97iNQBX7XZObNr/t7pKbJAvdw51JEBKrkc0fL1V9eGYsz+lyn
            GOSpYjmZpp9BFcQefPQ2NRXldfIDZwBNolAmSaWG3hK7M3RONpL5g1w00yCBuRu8
            tH/ZVT5fIU2DkCg7hQ6Bkv2mHpxlmHuGQb/HuM0/zwfOJFDYdY41iBWmTBiIZFm/
            meCAND2G9z+uCohm9PJjhKvSwa6qZxkoqb4TIVZ0nobIfAygWlc3n6DXQ1y52Sib
            BIpNHtECgYEA/DWc+wfvJcjYIKZhHgAymBwQOus36ykhLuELJ4Aq8kViNjaldKYw
            SJj9DMdYj5NuNpQDKbZ4BATfSSJroOdeYL9obNItOVMRewTS0xumCirzj4zXpkpr
            UbLxoIDa8Hh+LoRnbQkH5InYsP1oYvVViNBOdJWKzGORdbnplZKNbC8CgYEArQRp
            tcPQ1r49fXeqrc2iXjl9YHlEXMEHe4M9/YTWZFzJkMTfSkMASJSEcVzrbOhhCavZ
            Y5KFRGCG5wktY2D0QHtpVm0yVmpDDAEQxVIaHEB4HhX7uMWhBHtY43ugRzoJG9pE
            dAW/Hg49uz4u1/+ixzhk2sh0Qf/pBl+FFjQ84f0CgYAWCCTvdPD6LwJaT856DXBe
            A02TqAqZe11PuA7+Y17dDRyYOcvYVdAv91VbsWpWGH3vPJzOHwd66mYLAHvAcZW4
            A+B+aRnUQSJsya4VDPxDNR9Tse0AtM2NNIGRENCPYyc6rwxN5RUQbM5GH8znoCDZ
            s8C2xH18f1Iso5H5I/VAtwKBgFVahvfnqUA3S8h435esiXxoaiTMzl/fzlwta8iE
            3utWJw4nQWy2Tw5/TjNKvs3UegK2Z6FKqDoKUKLrkRukufqRp26+ogWlmHv0jpx5
            m23ylA9rkuodfQjj/P8EfxaEV/gInpqKNzWRmvyjeaKPd3NGq+KO32Or5v6A4vwI
            OzzVAoGBAL9xbXjMPZYHGzt1SWQoFzcB49QM06rOkZysAUX1GQYQSxEjMksCzUKx
            bzZ84P4LNuJQfJU3CpFfVlymxE43BgK9qJUYwaS96/NILSNhGlT0+F5hiRNLTXqu
            gIGvCPNHVKyWlkAl+cqH/NYO2uFu1mQxooJEmc4PIfF+sdEKYmJR
            -----END RSA PRIVATE KEY-----
        known_hosts: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
