secrets:
    db:
        username: <db_username>
        password: test1234
        flywayUsername: <db_username>
        flywayPassword: test1234
    egov-filestore:
        awskey: nsbufjbasnvvnkjd
        awssecretkey: bxjcsncajsb
    user:
        username: admin
        password: eGov@123
    egov-enc-service:
        master_password: demo
        master_salt: q7.fr.cr
        master_initialvector: 9J&asfgrU-H2
    egov-notification-sms:
        username: demo
        password: demo
    egov-pg-service:
        axis_merchant_accesscode: demo
        axis_merchant_id: demo
        axis_merchant_pwd: demo
        axis_merchant_secretkey: demo
        axis_merchant_user: demo
        payu_merchant_key: demo
        payu_merchant_salt: demo
    egov-notification-mail:
        mailsenderusername: demo@demo
        mailsenderpassword: demo
    egov-location:
        gmapskey: jbsdbvxmbsmnx
    kafka:
        clusterID: HshRPdVrWoB4kuTdEbawtq
    elasticsearch:
        password: 8fwbD6HbJh6HU0oddsHm8TEI
    oauth2-proxy:
        cookieSecret: qwgethjymnbv
        clientSecret: 3a08079easd9d8055470475696fd3baad5292
        clientID: QVbnq0L8npoyfxZs96wtBg==
    git-sync:
        ssh: |-
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpQIBAAKCAQEAkHKZKzrFjh9NtrKzh6u4MeCeBiug9eKTIswUTZbJGirGyJfF
            yEcSRTlO2MNY5icoT4eU8P6FKG8EtcKV7obX+onohW4K0L0Bbx5jqqqn/rJiwmtt
            68hYeYKIe1H950cJc/GL97UD0a98T1FUVUxQZ710HI3NKtlJX6dq7JC8fekoez7P
            02Hyvu25IAeJ5pzcTixCX5tcDCHUDTeKShhgB9kesvpKZVeDmFg0/HMi6T3Lx8vx
            xEz5Z6gMD3c310Ucx1B9PnIyolueUUILPaDOZxW6hK598gUaTRXQzDehcM0Bh6R2
            7QmJzz7eBa+KgepljsrY8l4lL9+pCqT/UnIdGQIDAQABAoIBAAbnw5TCeYFC09dB
            Eb4RonuX7lYDLe2zSC9orCvNYo3Cr8AVKVpas2/lvnQ0WoKeKpoqtB8VO85kCEic
            JcjCX37Vquz+BrxV3MSwIjmdcOyHIJuEwTt9V2VvrRCgKdAtoDEPwg40dBtJFVtB
            WxO80zcyYmOfD8jVnGFbQoxOmwQ117ws67/KaJv5ETR3clNVQr7dxPkj7xMjtgiR
            16I96FfTv06QhNPdaECx+RoWVCLnqMjUphOXlK1o/rJ8jC3ZfdmWKMGYTAmSVC5K
            KvtbaN3hlUT8FZflXJ+ayR3sr2jb0hhfH9rwcSs3q16ZOryHrOps7OQ2AEiuq2N9
            Y4oumZECgYEA1+lstVCc5Baq9e9hPwMrbgAk13C6NZxPg3jCH8ef2iVXpz5MixCO
            q+wMEdxLmltmnAojXHhv2KOvEbiz1V/uZNrXBsTSoriohgbb82U1B0yIeGuWWDaN
            fgKiNIO8d36mk2oZyEL9wdjVELjWP9AXw1hNR4JQrQkk4dV1AqxD+e0CgYEAq0Rj
            EJDPpaCwKKGaN2CoanQ6QUSaC02FP1Dk2l1pW9NM1Xq9UnYFi0PaP7gu3n6ot+mq
            ToPdGyDSpZDCBdr4nLUnzkCqn4fHtMxKXvj928C3AAd/YfRsX6oFFBhJs5WNjY7w
            OvTebDqnsNfKOsfZ3pbCQtIdR+LU63lvJZ8PWl0CgYEAzV25iLykfk8RTdvjI4xg
            QsDgSgtvEo8bEnJKMvAtm9DpDqqzI5McIWrkEBj50FgfwUvjVpE30VffrXuBkfMt
            TcDZxhZwQ1Zg9RqRG3GofsjNBb1Pw5gf/TuEDW9AVGijCJRi8ZjGxRr5jm5BW3ET
            KTtURjAtjGimLChco642+gECgYEAl72ai+XRo+xvx0AO07u228KojoVKenMveH6i
            lPooS+w1afs6XCInHVF7v/Ley9CqiW/krXXVY6C8IWbVEL0GgklawDm5Mmjpvr01
            s1mmCZqASO1bph0aG9QWdcxjGFKLvP0EySeFHZ0GT/+QtG23Eai+6tcgjD1j6lGH
            8Www/R0CgYEAqeSfTvYXkgJUwArkBxwvWUxBjAHxi3pNRJtlzkUUR9hsqHYKM2pN
            wsTSmGy2kudttAydbgF73uuKUf6YHrm942uS4Q6DZww4fBV7OL1qbKvoEMSRMqoN
            ZKbufc+5ooOXefIz/n5MdJL/2N/CytMpUA/G8mt1T0I2b0Yeqhn3efo=
            -----END RSA PRIVATE KEY-----
        known_hosts: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
